services:
  inv-server:
    environment:
      DATABASE_URL: $DATABASE_URL
    ports:
        - 3000:3000
    image: docker pull ghcr.io/crateme-ul/inv-backend:main

  inv-ui:
    ports:
        - 8080:8080
    image: docker pull ghcr.io/crateme-ul/inv-frontend:main
