services:
  web:
    image: nginx:1.27.0
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - inv

  inv-db:
    image: "postgres:16.3"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - inv

  inv-server:
    environment:
      DATABASE_URL: ${DATABASE_URL}
    image: ghcr.io/crateme-ul/inv-backend:main
    networks:
      - inv

  inv-ui:
    environment:
      VITE_API_ENDPOINT: ${VITE_API_ENDPOINT}
    image: ghcr.io/crateme-ul/inv-frontend:main
    networks:
      - inv

volumes:
  db-data:

networks:
  inv:
    driver: bridge
