services:
  inv-db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
  inv-server:
    environment:
      DATABASE_URL: $DATABASE_URL
    ports:
      - 3000:3000
    image: ghcr.io/crateme-ul/inv-backend:main

  inv-ui:
    ports:
      - 8080:8080
    image: ghcr.io/crateme-ul/inv-frontend:main
