apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: example-ingressroute
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`example.local`)
      kind: Rule
      services:
        - name: your-service-name
          port: 80
  tls:
    secretName: inv-tls
