# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: webserver-ingress
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: web
# spec:
#   rules:
#   - host: monequilibre.inventaire.local
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: webserver-service
#             port:
#               number: 80
