services:
  inv-db:
    container_name: inv-db
    image: postgres:16.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - inv-db-data:/var/lib/postgresql/data
    networks:
      - inv

  inv-server:
    container_name: inv-server
    # image: ghcr.io/crateme-ul/inv-backend:main
    build:
      context: .
      dockerfile: ./dockerfile.backend
    restart: unless-stopped
    depends_on:
      - inv-db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - inv

  inv-nginx:
    container_name: inv-nginx
    # image: nginx:1.27.0
    build:
      context: .
      dockerfile: ./dockerfile.nginx

    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - inv

volumes:
  inv-db-data:

networks:
  inv:
    driver: bridge
