services:
  inv-db:
    container_name: inv-db
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - inv-db-data:/var/lib/postgresql/data
    networks:
      - inv

  inv-server:
    container_name: inv-server
    # image: ghcr.io/crateme-ul/inv-backend:main
    build:
      context: .
      dockerfile: ./dockerfile.backend
    depends_on:
      - inv-db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DIR: ${APP_DIR}
      RUST_LOG: ${RUST_LOG}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    networks:
      - inv

  inv-nginx:
    container_name: inv-nginx
    # image: nginx:1.27.0
    build:
      context: .
      dockerfile: ./dockerfile.nginx
    environment:
      VITE_API_ENDPOINT: ${VITE_API_ENDPOINT}

    ports:
      - 80:80
    networks:
      - inv

volumes:
  inv-db-data:

networks:
  inv:
    driver: bridge
