services:
  inv-db:
    container_name: inv-db
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - inv-db-data:/var/lib/postgresql/data
    # networks:
    #   - inv

  inv-backend:
    container_name: inv-backend
    image: ${BACKEND_IMAGE_NAME}
    depends_on:
      - inv-db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DIR: ${APP_DIR}
      RUST_LOG: ${RUST_LOG}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    # networks:
    #   - inv

  inv-frontend:
    container_name: inv-frontend
    image: ${FRONTEND_IMAGE_NAME}
    depends_on:
      - inv-backend
    ports:
      - 80:80
    # networks:
    #   - inv

volumes:
  inv-db-data:
# networks:
#   inv:
#     driver: overlay
