FROM node:22.4-bullseye-slim AS frontend

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY ./INV-frontend .
RUN npm run build

FROM nginx:1.27.0

COPY --from=frontend /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf