FROM node:22.4-bullseye-slim AS frontend

WORKDIR /app
COPY ./INV-Frontend .

RUN pwd && ls -la
RUN npm ci
RUN npm run build

FROM nginx:1.27.0
RUN pwd && ls -la
COPY --from=frontend /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf