apiVersion: v1
kind: Service
metadata:
  name: inv-server
  labels:
    app: inv
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: inv
    tier: backend
