apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app: inv
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inv
      tier: frontend
  template:
    metadata:
      labels:
        app: inv
        tier: frontend
    spec:
      containers:
        - name: inv-frontend
          image: ghcr.io/crateme-ul/inv-frontend:inv-142-add-place-type-filter-and-their-tag
          env:
            - name: VITE_API_ENDPOINT
              value: http://localhost/api/v1
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      imagePullSecrets:
        - name: ghcr-secret
