# Use the latest version of the Rust base image
FROM rust:latest

# Set the working directory in the container
WORKDIR /usr/src/inv-server

# Copy the Rust project files to the working directory
COPY . .

# Build the Rust app
RUN cargo build --release

# Set the command to run the compiled Rust app
CMD ["./target/release/app"]