FROM rust:1.79-slim-bullseye

# Install dependencies
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    netcat \
    && rm -rf /var/lib/apt/lists/*

# Create a new directory for the project
WORKDIR /usr/src/inv-server

# Copy the project files into the Docker image
COPY . .

# Copy the entrypoint script
COPY entrypoint.sh /usr/src/inv-server/entrypoint.sh
RUN chmod +x /usr/src/inv-server/entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/usr/src/inv-server/entrypoint.sh"]