[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
repository = { path = "../repository" }
resource = { path = "../resource" }
tokio = { version = "1.40.0", features = ["full"] }
