[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
resource = { path = "../resource" }
tokio = { version = "1.40.0", features = ["full"] }
axum = "0.7.6"
