[package]
name = "excel_to_sql"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.25.0" # Make sure this version matches your use case
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
