services:
  # TODO: update to suppport web, as web is faster so we should be able to healthcheck to avoid that db connection fails when starting app. https://docs.docker.com/compose/startup-order/
  # web:
  #   build: .
  #   ports:
  #     - "80:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: ["python", "app.py"]
 
  # db:
  #     image: postgres
  #     restart: always
  #     environment:
  #       POSTGRES_PASSWORD: example
  #     healthcheck:
  #     test: [“CMD-SHELL”, “pg_isready”]
  #     interval: 1s
  #     timeout: 5s
  #     retries: 10
 
  # adminer:
  #     image: adminer
  #     restart: always
  #     ports:
  #       - 8080:8080


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

# similar to DBreave maybe to remove
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  pgdata:

