services:
  inv-db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
    networks:
      - inv

  inv-server:
    ports:
        - 3000:3000
    image: inv-server
    networks:
      - inv
      
networks:
  inv:

