[package]
name = "repository"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
sqlx = { version = "0.8.2", features = ["runtime-tokio", "postgres"] }
once_cell = "1.19.0"
