[package]
name = "repository"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }

sqlx = { version = "0.7.4", features = ["runtime-tokio", "postgres"] }
axum = "0.7.5"
once_cell = "1.19.0"
dotenv = "0.15.0"
